// numstr.cpp -- following number input with line input
#include<iostream>
int main()
{
	using namespace std;
	cout << "What year was your house build?\n";
	int year;
	cin >> year;
	cout << "What is its street address?\n";
	char address[80];
	cin.getline(address, 80);
	cout << "Year built: " << year << endl;
	cout << "Address: " << address << endl;
	cout << "Done!\n";
	return 0;
}

// You never get the opportunity to enter the address. The problem is what when 'cin' reads
// this year, it leaves the newline generated by the Enter key in the input queue. Then 'cin.getline()'
// reads the newline as an empty line and assigns a null string to the address array.